<?php
/**
 * @author      Open Source Team
 * @copyright   2022 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

/** @var \Woocommerce\Pagarme\Block\Checkout\ThankYou\Billet $this */

declare( strict_types=1 );

if (!function_exists('add_action')) {
    exit(0);
}
?>
<?php if ($this->getBilletUrl()) : ?>
    <p>
        <?php _e('If you have not yet received the boleto, please click the button below to print.', 'woo-pagarme-payments'); ?>
    </p>
    <a href="<?= $this->getBilletUrl() ?>" target="_blank" class="payment-link">
        <?php _e('Print', 'woo-pagarme-payments'); ?>
    </a>
<?php else : ?>
    <p>
        <?php
        printf(
            __('The status of your transaction is %s.', 'woo-pagarme-payments'),
            '<strong>' . strtoupper(
                __(
                    'Failed',
                    'woo-pagarme-payments'
                )
            ) . '</strong>'
        );
        ?>
    </p>
<?php endif; ?>
