<?php
/**
 * @author      Open Source Team
 * @copyright   2022 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

/** @var \Woocommerce\Pagarme\Block\Checkout\ThankYou\CreditCard $this */

declare( strict_types=1 );

if (!function_exists('add_action')) {
    exit(0);
}
?>
<?= $this->createBlock(
    '\Woocommerce\Pagarme\Block\Checkout\ThankYou\StatusTransaction',
    'pagarme.checkout.thankyou.statustransaction',
    [
        'message' => $this->getCharge() ? ucfirst($this->getCharge()->status) : null
    ]
)->toHtml() ?>
