<?php
/**
 * @author      Open Source Team
 * @copyright   2022 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

/** @var \Woocommerce\Pagarme\Block\Checkout\ThankYou\Voucher $this */

declare( strict_types=1 );

if (!function_exists('add_action')) {
    exit(0);
}
?>
<p>
    <?php
    /** phpcs:disable */
    printf(
        __('The status of your transaction is %s.', 'woo-pagarme-payments'),
        '<strong>' . strtoupper(
            __(
                $this->getChargeStatus() ? ucfirst($this->getChargeStatus()) : 'Failed',
                'woo-pagarme-payments'
            )
        ) . '</strong>'
    );
    /** phpcs:enable */
    ?>
</p>
