<?php
/**
 * @author      Open Source Team
 * @copyright   2022 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 * @link        https://pagar.me
 */

/** @var $this Text */

use Woocommerce\Pagarme\Block\Adminhtml\System\Config\Form\Field\Text;

if (!defined('ABSPATH')) {
    exit;
}
?>
<input type="text" id="<?php echo esc_attr($this->getId()); ?>"
       name="<?php echo esc_attr($this->getName()) ?>[<?php echo esc_attr($this->getId()); ?>]"
       value=" <?= $this->getCurrent() ?>"/>
<?php if ($this->getLabel()) : ?>
    <label for="<?php echo esc_attr($this->getId()); ?>"><?php echo esc_html($this->getLabel()); ?></label>
<?php endif; ?>
