<?php
/**
 * @author      Open Source Team
 * @copyright   2022 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

/** @var \Woocommerce\Pagarme\Block\Checkout\Payment\BilletAndCard $this */

declare(strict_types=1);

if (!function_exists('add_action')) {
    exit(0);
}
?>
<?= $this->createBlock(
        '\Woocommerce\Pagarme\Block\Checkout\Form\Billet',
        'pagarme.checkout.form.billet',
        [
            'payment_instance' => $this->getPaymentInstance(),
            'show_order_value' => true,
            'show_multicustomers_form' => true,
            'multicustomers_sequence' => 1
        ]
)->toHtml() ?>
<?= $this->createBlock(
        '\Woocommerce\Pagarme\Block\Checkout\Form\Card',
        'pagarme.checkout.form.card',
        [
            'payment_instance' => $this->getPaymentInstance(),
            'qty_cards' => $this->getQtyCards(),
            'show_order_value' => true,
            'show_multicustomers_form' => true,
            'multicustomers_sequence' => 2
        ]
)->toHtml() ?>
