<?php
/**
 * @author      Open Source Team
 * @copyright   2022 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

/** @var \Woocommerce\Pagarme\Model\Gateway $model */

declare( strict_types=1 );

use Woocommerce\Pagarme\Helper\Utils;
use Woocommerce\Pagarme\Core;

$model = current($args);
$cardQty = end($args);

if (!function_exists('add_action')) {
    exit(0);
}

wp_enqueue_script('pagarme-checkout-card', Core::plugins_url('assets/javascripts/front/checkout/model/payment/card.js'));
wp_localize_script(
    'pagarme-checkout-card',
    'wc_pagarme_checkout',
    ['config' => $model->getConfigDataProvider()]
);

$type = $model->payment;
$ref = $model->getPaymentInstace($type)->getReference();
?>
<?php for ($qty = 1; $qty <= $cardQty; $qty++) : ?>
    <fieldset id="pagarme-fieldset-<?= $type . '-' . $qty ?>" class="wc-credit-card-form wc-payment-form" data-pagarmecheckout-method="<?= $type ?>" data-pagarmecheckout="card" data-pagarmecheckout-card-num="<?= $qty ?>">
        <?php Utils::get_template('templates/checkout/payment/card/wallet', ['payment' => $model->getPaymentInstace($type), 'ref' => $qty]) ?>
        <div class="wc-credit-card-info" data-element="fields-cc-data">
            <div <?= Utils::get_component('pagarme-checkout'); ?> data-pagarmecheckout-app-id="<?= esc_attr($model->getPaymentInstace($type)->getConfig()->getPublicKey()); ?>">
                <p class="form-row form-row-wide">
                    <label for="card-holder-name">
                        <?php esc_html_e('Card Holder Name', 'woo-pagarme-payments'); ?> <span class="required">*</span>
                        <input id="card-holder-name" onkeydown="return /[a-z, ]/i.test(event.key)" data-element="card-holder-name" data-required="true" class="input-text" style="font-size: 1.41575em" data-pagarmecheckout-element="holder_name">
                    </label>
                </p>
                <p class="form-row form-row-wide">
                    <label for="card-number"><?php esc_html_e('Card number', 'woo-pagarme-payments'); ?> <span class="required">*</span></label>
                    <input id="card-number" data-element="pagarme-card-number" class="input-text wc-credit-card-form-card-number pagarme-card-form-card-number" data-mask="0000 0000 0000 0000" placeholder="•••• •••• •••• ••••" data-required="true" style="background-image: none" data-pagarmecheckout-element="number">
                    <input type="hidden" name="brand" data-pagarmecheckout-element="brand-input" />
                    <span name="brand-image" data-pagarmecheckout-element="brand"></span>
                </p>
                <p class="form-row form-row-first">
                    <label for="card-expiry">
                        <?php esc_html_e('Expiration Date (MM/YY)', 'woo-pagarme-payments'); ?>
                        <span class="required">*</span>
                    </label>
                    <input id="card-expiry" data-element="card-expiry" class="input-text wc-credit-card-form-card-expiry pagarme-card-form-card-expiry" data-mask="00 / 00" data-required="true" placeholder="<?php esc_html_e('MM / YY', 'woo-pagarme-payments'); ?>" data-pagarmecheckout-element="exp_date">
                </p>
                <p class="form-row form-row-last">
                    <label for="card-cvc">
                        <?php esc_html_e('Card code', 'woo-pagarme-payments'); ?> <span class="required">*</span>
                    </label>
                    <input id="card-cvc" data-element="card-cvc" data-mask="0000" class="input-text wc-credit-card-form-card-cvc pagarme-card-form-card-cvc" maxlength="4" placeholder="CVC" data-required="true" data-pagarmecheckout-element="cvv">
                </p>
            </div>
            <p class="form-row form-row-wide">
                <?php Utils::get_template('templates/checkout/payment/card/installments', ['payment' => $model->getPaymentInstace($type)]) ?>
            </p>
            <?php Utils::get_template('templates/checkout/payment/card/field-save', ['payment' => $model->getPaymentInstace($type)]); ?>
            <?php Utils::get_template('templates/checkout/field-enable-multicustomers', compact('ref', 'type')); ?>
        </div>
    </fieldset>
<?php endfor; ?>
<?php Utils::get_template('templates/checkout/multicustomers-form', compact('ref', 'type')); ?>
<script src="<?= esc_url(Core::plugins_url('assets/javascripts/front/checkout/model/payment/card/tokenize.js')); ?>" type="application/javascript"> </script>
<script src="<?= esc_url(Core::plugins_url('assets/javascripts/front/checkout/model/payment/card.js')); ?>" type="application/javascript"> </script>
