<?php
/**
 * @author      Open Source Team
 * @copyright   2022 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

/** @var \Woocommerce\Pagarme\Block\Checkout\Payment\CreditCard $this */

declare( strict_types=1 );

if (!function_exists('add_action')) {
    exit(0);
}
$y = $this->getQtyCards();
$x = $this->getPaymentInstance();

$this->createBlock(
    '\Woocommerce\Pagarme\Block\Checkout\Form\Card',
    'pagarme.checkout.form.card',
    [
        'payment_instance' => $x,
        'qty_cards' => $y
    ]
)->toHtml();
