<?php
/**
 * @author      Open Source Team
 * @copyright   2022 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

/** @var \Woocommerce\Pagarme\Block\Checkout\Payment\Pix $this */

declare( strict_types=1 );

if (!function_exists('add_action')) {
    exit(0);
}
?>
<?= $this->createBlock(
    '\Woocommerce\Pagarme\Block\Checkout\Form\Pix',
    'pagarme.checkout.form.pix',
    [
        'payment_instance' => $this->getPaymentInstance(),
        'show_message' => true,
        'show_image' => true
    ]
)->toHtml() ?>
