<?php
/**
 * @author      Open Source Team
 * @copyright   2022 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

/** @var \Woocommerce\Pagarme\Model\Gateway $model */

declare( strict_types=1 );

if (!function_exists('add_action')) {
    exit(0);
}

use Woocommerce\Pagarme\Helper\Utils;

$type = $model->payment;
$ref = $model->getPaymentInstace($type)->getReference();
?>
<fieldset class="wc-credit-card-form wc-payment-form">
    <p>
        <?= $model->getPaymentInstace($type)->getMessage() ?>
    </p>
    <label>
        <?php
        printf(
            '<img class="logo" src="%1$s" alt="%2$s" title="%2$s" />',
            $model->getPaymentInstace($type)->getImage(),
            esc_html__('Pix', 'woo-pagarme-payments')
        );
        ?>
    </label>
    <?php Utils::get_template('templates/checkout/field-enable-multicustomers', compact('ref', 'type')); ?>
</fieldset>
<?php Utils::get_template('templates/checkout/multicustomers-form', compact('ref', 'type')); ?>
