<?php
/**
 * @author      Open Source Team
 * @copyright   2022 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

/** @var \Woocommerce\Pagarme\Model\Gateway $model */

declare( strict_types=1 );

if (!function_exists('add_action')) {
    exit(0);
}

use Woocommerce\Pagarme\Core;
use Woocommerce\Pagarme\Helper\Utils;

$ref  = sha1((string)random_int(1, 1000));
$type = $model->payment;
?>
<fieldset class="wc-credit-card-form wc-payment-form">
    <p>
        O QR Code para seu pagamento através de PIX será gerado após a confirmação da compra. Aponte seu celular para a tela para capturar o código ou copie e cole o código em seu aplicativo de pagamentos.
    </p>
    <label>
        <?php
        printf(
            '<img class="logo" src="%1$s" alt="%2$s" title="%2$s" />',
            esc_url(Core::plugins_url('assets/images/pix.svg')),
            esc_html__('Pix', 'woo-pagarme-payments')
        );
        ?>
    </label>
    <?php Utils::get_template('templates/checkout/field-enable-multicustomers', compact('ref', 'type')); ?>
</fieldset>
<?php Utils::get_template('templates/checkout/multicustomers-form', compact('ref', 'type')); ?>
