<?php
/**
 * @author      Open Source Team
 * @copyright   2022 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

/** @var \Woocommerce\Pagarme\Block\Checkout\Form\Wallet $this */

declare( strict_types=1 );

if (!function_exists('add_action')) {
    exit(0);
}
?>
<?php if ($this->getConfig()->getIsEnableWallet() && $this->getPaymentInstance()->getCards()) : ?>
    <?php esc_html_e('Credit cards save', 'woo-pagarme-payments'); ?><br>
    <select name="<?= $this->getElementId('wallet-id') ?>" id="<?= $this->getElementId('wallet-id') ?>" data-action="select-card-wallet" data-installments-type="<?= intval($this->getPaymentInstance()->getConfig()->getCcInstallmentType()); ?>" data-element="choose-credit-card">
        <?php foreach ($this->getPaymentInstance()->getCards() as $card) : ?>
            <?php
                printf(
                    '<option data-brand="%3$s" value="%2$s">(%1$s) •••• •••• •••• %4$s</option>',
                    esc_html(strtoupper($card->getBrand()->getName())),
                    esc_attr($card->getPagarmeId()->getValue()),
                    esc_html(strtolower($card->getBrand()->getName())),
                    esc_html($card->getLastFourDigits()->getValue())
                );
            ?>
        <?php endforeach; ?>
    </select>
<?php endif; ?>
