<?php
/**
 * @author      Open Source Team
 * @copyright   2022 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

/** @var \Woocommerce\Pagarme\Block\Order\Transaction\Boleto $this */

declare( strict_types=1 );

if (!function_exists('add_action')) {
    exit(0);
}
?>
<?php if ($this->getBilletUrl()) : ?>
    <tr>
        <th><?= __('Billet', 'woo-pagarme-payments'); ?>:</th>
        <td>
            <p>
                <?=
                __(
                    'If you have not yet received the boleto, please click the button below to print.',
                    'woo-pagarme-payments'
                );
                ?>
            </p>
            <button id="pagarme-billet-button"
                    data-pagarme-billet-url="<?= $this->getBilletUrl() ?>"
                    class="pagarme-payment-button">
                <?php _e('Print', 'woo-pagarme-payments'); ?>
            </button>
            <script type="text/javascript">
                $ = jQuery;
                $('#pagarme-billet-button').on('click', function(e){
                    e.preventDefault();
                    // Safari is blocking any call to window.open() which is made inside an async call.
                    setTimeout(() => {
                        window.open($(this).attr('data-pagarme-billet-url'), '_blank');
                    })
                });
            </script>
        </td>
    </tr>
<?php endif; ?>
