<?php
/**
 * @author      Open Source Team
 * @copyright   2022 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

/** @var \Woocommerce\Pagarme\Block\Order\Transaction\Boleto $this */

declare( strict_types=1 );

if (!function_exists('add_action')) {
    exit(0);
}
?>
<?php if ($this->getBilletUrl()) : ?>
    <tr>
        <th><?= __('Billet', 'woo-pagarme-payments'); ?>:</th>
        <td>
            <p>
                <?=
                __(
                    'If you have not yet received the boleto, please click the button below to print.',
                    'woo-pagarme-payments'
                );
                ?>
            </p>
            <button id="pagarme-billet-button"
                    data-pagarme-billet-url="<?= $this->getBilletUrl() ?>"
                    class="button">
                <?php _e('Print', 'woo-pagarme-payments'); ?>
            </button>
        </td>
    </tr>
<?php endif; ?>
