<?php
/**
 * @author      Open Source Team
 * @copyright   2022 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

/** @var \Woocommerce\Pagarme\Block\Order\Transaction\DefaultTransaction $this */

declare( strict_types=1 );

if (!function_exists('add_action')) {
    exit(0);
}
?>
<tr>
    <th><?= __('Payment Type', 'woo-pagarme-payments'); ?>:</th>
    <td><?= __($this->getTransactionType(), 'woo-pagarme-payments'); ?></td>
</tr>
