<?php
/**
 * @author      Open Source Team
 * @copyright   2023 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

/** @var \Woocommerce\Pagarme\Block\Order\Email $this */

declare(strict_types=1);

use Woocommerce\Pagarme\Block\Order\EmailCharge;

if (!function_exists('add_action')) {
    exit(0);
}
?>
<?php if ($this->isPagarmePaymentMethod($this->getOrder())) : ?>
    <h2><?= __('Payment Data', 'woo-pagarme-payments'); ?></h2>
    <div id="pagarme-payment-detail" style="margin-bottom: 40px;">
        <p>> email.phtml</p>
        <?php if ($this->getCharges()) : ?>
            <?php foreach ($this->getCharges() as $charge) : ?>
                <?=
                $this->createBlock(EmailCharge::class,
                    'pagarme.order.email',
                    [
                        'charge' => $charge,
                        // 'template' => 'templates/order/email-charge'
                    ]
                )->toHtml()
                ?>
            <?php endforeach; ?>
        <?php else : ?>
            <p>
                <?= __('No records found.', 'woo-pagarme-payments'); ?>
            </p>
        <?php endif; ?>
    </div>
<?php endif; ?>
