<?php
/**
 * @author      Open Source Team
 * @copyright   2022 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

/** @var \Woocommerce\Pagarme\Model\Payment\CreditCard|\Woocommerce\Pagarme\Model\Payment\Voucher $payment */

declare( strict_types=1 );

if (!function_exists('add_action')) {
    exit(0);
}

$payment = $args['payment'];
?>
<?php if ($payment->getIsEnableWallet()) : ?>
    <p class="form-row form-row-wide" data-element="save-cc-check">
        <label for="save-card">
            <input type="checkbox" id="save-card" name="save_card" value="1" <?php checked($payment->getCustomer()->save_credit_card, true); ?>>
            <?php esc_html_e('Save this card for future purchases', 'woo-pagarme-payments'); ?>
        </label>
    </p>
<?php endif; ?>
