<?php
/**
 * @author      Open Source Team
 * @copyright   2022 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

/** @var \Woocommerce\Pagarme\Model\Payment\CreditCard|\Woocommerce\Pagarme\Model\Payment\Voucher $payment */

declare( strict_types=1 );

if (!function_exists('add_action')) {
    exit(0);
}

global $woocommerce;

use Woocommerce\Pagarme\Helper\Utils;
use Woocommerce\Pagarme\View\Checkouts;

$payment = $args['payment'];
$total = $woocommerce->cart->total;
$installmentType = intval($payment->getConfig()->getCcInstallmentType());
?>
<label for="installments_card">
    <?php esc_html_e('Installments quantity', 'woo-pagarme-payments'); ?><span class="required">*</span>
</label>
<select id="installments_card" <?= Utils::get_component('installments'); ?> data-total="<?= esc_html($total); ?>" data-type="<?= $installmentType; ?>" data-action="select2" data-required="true" data-element="installments" name="installments_card" style="font-size: 1.41575em">
    <?php if ($installmentType !== 2) : ?>
        <?php foreach  (Checkouts::render_installments($total) as $options) : ?>
            <option value="<?= $options['value'] ?>"><?= $options['content'] ?></option>
        <?php endforeach; ?>
    <?php else : ?>
        <option value="">...</option>
    <?php endif; ?>
</select>
