name: CD REUSABLE

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      wordpress_image_version:
        required: false
        type: string
        default: latest
      woocommerce_version:
        required: false
        type: string
        default: latest-stable
      woocommerce_extra_checkout_fields_version:
        required: false
        type: string
        default: latest-stable
      wp_mail_catcher_version:
        required: false
        type: string
        default: latest-stable
permissions:
  contents: read
jobs:
  publish:
    runs-on: small-runner
    steps:
      - name: Checkout Code
        uses: stone-payments/approved-actions/actions/checkout/v4@stable
        with:
          path: 'plugins/pagarme-payments-for-woocommerce'
      - name: Download other plugins
        run: |
          chmod +x plugins/pagarme-payments-for-woocommerce/.github/data/install-zips.sh \
            && bash plugins/pagarme-payments-for-woocommerce/.github/data/install-zips.sh -w ${{ inputs.woocommerce_version }} -f ${{ inputs.woocommerce_extra_checkout_fields_version }} -m ${{ inputs.wp_mail_catcher_version }}
      - name: Log in to Docker Hub
        uses: stone-payments/approved-actions/docker/login-action/v1@stable
        with:
          registry: ${{ secrets.DOCKER_ACCOUNT }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: stone-payments/approved-actions/docker/metadata-action/v4@stable
        with:
          images: ${{ secrets.DOCKER_ACCOUNT }}/woocommerce-pagarme
      - name: Build and push Docker image
        uses: stone-payments/approved-actions/docker/build-push-action/v3@stable
        with:
          build-args: |
            WORDPRESS_IMAGE_VERSION=${{ inputs.wordpress_image_version }}
          context: .
          file: plugins/pagarme-payments-for-woocommerce/.github/data/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_ACCOUNT }}/woocommerce-pagarme:${{ inputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
