<?php
/**
 * @author      Open Source Team
 * @copyright   2022 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

/** @var \Woocommerce\Pagarme\Block\Order\Transaction\CreditCard $this */

declare( strict_types=1 );

if (!function_exists('add_action')) {
    exit(0);
}
?>
<?php if ($this->getCardDetails()) : ?>
    <?php foreach ($this->getCardDetails() as $label => $value) : ?>
        <tr>
            <th><?= $label ?>:</th>
            <td><?= $value ?></td>
        </tr>
    <?php endforeach; ?>
<?php endif; ?>
